### PR TITLE
*+ voltage/backend PKTIDX++

### PR DESCRIPTION
**Pull request by radonnachie**
- DIRECTIO padding based on header
- record(...load_template=...) argument
- NPOLS not set to 4 instead of 2
- self.time_per_block based on integer self.samples_per_block (previously was real division)

### CODE REVIEW

**Comment by radonnachie** [comment]
The `NPOLS=4 if NPOLS==2 else NPOLS` conditional assignment is something I'm going to try stamp out within the community. It is integral to the calculation of NTIME from BLOCSIZE, so it's best that it accurately represents the num_pols of the stream.

**Comment by radonnachie** [comment]
Point me at any docs you want me to update. Should probably get a version bump too.

**Comment by bbrzycki** [comment]
Cool stuff! 

Doing a quick scan, it looks like most of the changes are under the hood / more flexible functionality? There isn't anything that would have to be _changed_, afaik, but maybe some details about how the header is handled here (https://setigen.readthedocs.io/en/main/voltages.html) could be useful? Given the existing structure of the docs, though, I'm not sure where, to be honest. I think we can go ahead and merge, unless you think there's a good way to highlight this in the external docs.

Depending on the impact of the changes, we can bump to either 2.3.2 or 2.4.0.

[The only other relevant external documentation would be the Jupyter tutorials, but I don't see anything in this pull request that would break backward compatibility, so I'm assuming it's fine. On this note, the voltage module really could use dedicated test cases so that we don't have to manually verify these things..]

**Comment by radonnachie** [comment]
Roger. It's backwards compatible so I've bumped to 2.3.2.

I just wanted to note the `load_template` argument, as I didn't expect those key-values in the output. (hope my rst is right, I didn't build locally)

**Comment by bbrzycki** [comment]
Merged!

**Pull request merged**
